### ISSUE TITLE
Mouse display problem

### ISSUE THREAD

**Issue by sam8890** [hecomi/uDesktopDuplication#28]
Hello，Can you answer a question which I want to ask and which is puzzling me?
When the mouse is hidden，The mouse will appear in the upper left corner on capture image

**Comment by hecomi** [comment]
Thanks for reporting the bug. I found a problem about the cursor and fixed it, but have not released yet because I wasn't able to reproduce the bug in my environment. Could you check the following package in your environment?
[uDesktopDuplication-v1.6.1.zip](https://github.com/hecomi/uDesktopDuplication/files/2727032/uDesktopDuplication-v1.6.1.zip)

**Comment by sam8890** [comment]
thanks for your reply，Use the latest version (uDesktopDuplication-v1.6.1) ，the problem has been solved,Thank you very much
