### ISSUE TITLE
Ignoring Current Window

### ISSUE THREAD

**Issue by erherhh4herh** [hecomi/uDesktopDuplication#8]
Excuse me for my ignorance if this is already possible. But can I ignore the standalone's window from the display texture? I would like to do this because I want to give the player the ability to manipulate their desktop from the application.

Please and thank you,
erherhh4herh.

**Comment by hecomi** [comment]
Sorry, it is basically impossible because the Desktop Duplication API provides the texture just same as what you see in your desktop screen. So I think it is possible only in case that the player has two or more monitors and manipulate one from another one, or in case that the player see his/her desktop through HMD.
